# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-16 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='station',
            field=models.ForeignKey(default=1, help_text='The station which owns this calendar', on_delete=django.db.models.deletion.CASCADE, to='stations.Stations'),
        ),
        migrations.AddField(
            model_name='event',
            name='color_event',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Color event'),
        ),
    ]
