# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g. 'America/Detroit'. See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones", max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='timezone',
            field=models.ForeignKey(default=1, help_text='The timezone region name for this calendar', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Timezone'),
        ),
    ]
