# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-12 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestreamurl',
            name='url',
        ),
        migrations.AddField(
            model_name='calendar',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices=[(b'America/Detroit', 'Eastern'), (b'America/Chicago', 'Central')], default='America/Detroit', help_text='used only for generating recurring event occurrences'),
        ),
        migrations.AddField(
            model_name='livestreamurl',
            name='name',
            field=models.CharField(blank=True, help_text='A reference name for the stream', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='livestreamurl',
            name='page_url',
            field=models.URLField(help_text='The url of the livestream page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='livestreamurl',
            name='stream_url',
            field=models.URLField(help_text='The the stream url to be embedded', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(help_text='e.g. 2017-1-1 13:30', verbose_name='start'),
        ),
    ]
