# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, help_text='Image url to represent the event', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='image',
            field=models.URLField(blank=True, help_text='Image url to represent the event', max_length=1000, null=True),
        ),
    ]
