# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-06 14:07
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices=[(b'America/Detroit', 'Eastern'), (b'America/Chicago', 'Central')], default='America/Detroit', help_text='used only for generating recurring event occurrences'),
        ),
    ]
