# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_calendar_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(help_text='e.g. 2017-1-1 13:30', verbose_name='start'),
        ),
    ]
