# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-30 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20161130_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timezone',
            options={'verbose_name': 'timezone', 'verbose_name_plural': 'timezones'},
        ),
    ]
