# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-17 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160816_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='station',
            field=models.ForeignKey(help_text='The station which owns this calendar', on_delete=django.db.models.deletion.CASCADE, to='stations.Stations'),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.Calendar', verbose_name='calendar'),
        ),
    ]
