# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-30 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20161130_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='livestreamUrl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.LivestreamUrl'),
        ),
    ]
