# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20160817_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='color_event',
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Calendar', verbose_name='calendar'),
        ),
    ]
