# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-12 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20161211_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreamurl',
            name='name',
            field=models.CharField(blank=True, help_text='A reference name for the stream', max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='livestreamurl',
            name='url',
            field=models.URLField(help_text='The stream url to be embedded', max_length=1000),
        ),
    ]
