# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-30 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20161130_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='livestreamUrl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.LivestreamUrl'),
        ),
    ]
