# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-21 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20160901_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='url'),
        ),
    ]
