# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20161212_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestreamurl',
            name='url',
        ),
        migrations.AddField(
            model_name='livestreamurl',
            name='page_url',
            field=models.URLField(help_text='The url of the livestream page', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='livestreamurl',
            name='stream_url',
            field=models.URLField(help_text='The the stream url to be embedded', max_length=1000, null=True),
        ),
    ]
