# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-01 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20161130_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='timezone',
        ),
    ]
