# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-21 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('schedule', '0005_auto_20161121_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestreamUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('station', models.ForeignKey(help_text='The station who owns this url', on_delete=django.db.models.deletion.CASCADE, to='stations.Stations')),
            ],
            options={
                'verbose_name': 'livestreamUrl',
                'verbose_name_plural': 'livestreamUrls',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='url',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='url',
        ),
    ]
