# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-01 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gduser', '0006_auto_20161201_1438'),
        ('schedule', '0006_remove_calendar_timezone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timezone',
        ),
    ]
