# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-22 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20161121_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='livestreamUrl',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.LivestreamUrl'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='livestreamUrl',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.LivestreamUrl'),
        ),
    ]
